# Generated by Django 3.2.10 on 2022-03-26 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='firsr_name',
            new_name='first_name',
        ),
    ]
