# Generated by Django 3.2.10 on 2022-03-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_rename_firsr_name_customer_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='id_service',
            field=models.ManyToManyField(to='service.Service'),
        ),
        migrations.DeleteModel(
            name='Order_Service',
        ),
    ]
